name: Lint

on:
  push:
    paths:
      - '**.py'
      - .github/workflows/lint.yml

jobs:
  flake8_py3:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      uses: py-actions/flake8@v2
      with:
        plugins: "flake8-github"
        args: "--format github"